### ISSUE TITLE
Scanning for iBeacons (regions unknown)

### ISSUE THREAD

**Issue by cloudbreakstudios** [ObjectivityLtd/beacon_monitoring#15]
I want to be able to detect all iBeacons within range and print out their details (UUID, major, minor etc).  I do not know the device details up front i.e. the region.

I see that the package is detecting my iBeacon but i see in debug "This region (id1: 8492e75f-4fd6-469d-b132-043fe94921d8) does not match beacon: id1: 6e6e6974-7379-7141-b695-380958a51a5a id2: 59999 id3: 9999"

Is there a method I have missed where I can get this data and use it?

**Comment by wwwdata** [comment]
You need to know the iBeacon ID in advance to monitor beacons. That is how the Location SDK is working on the native Platforms. I think the reasoning behind this is: if you could monitor all beacons near you, you could build up a very large location network and abuse that feature a lot. So at least for the CoreLocation Framework on iOS, you must register the Identifiers before, and the limit is also 20 for this. Check the documentation from Apple here: 
https://developer.apple.com/documentation/corelocation/cllocationmanager/1423656-startmonitoring/
`CLRegion` can then for example be a `CLBeaconRegion` or a `CLCircularRegion` for GPS.

**Comment by wwwdata** [comment]
https://developer.apple.com/documentation/corelocation/determining_the_proximity_to_an_ibeacon_device

Is also interesting to read. In fact it is not that bad that you can only monitor 20 regions in iOS. Because a region can be a "wildcard" for many beacons.

A common strategy can be:
- Assign a unique UUID for all beacons in your company to all of your beacons
- use the major and minor numbers to distinguish between them. Those numbers are 16bit unsigned integers, so you have a lot of them
- You can then monitor for the company UUID and still distinguish between a lot of beacons

**Comment by MadDaelim** [comment]
Thank you for your help @wwwdata.
